# Generated by Django 3.2 on 2021-04-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='view_counter',
            field=models.IntegerField(default=0),
        ),
    ]
