# Generated by Django 3.2 on 2021-04-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_base', '0002_auto_20210416_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='accounts',
            new_name='participants',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='finished_at',
            new_name='finish_at',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='created_at',
            new_name='start_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='referenced_account',
        ),
        migrations.RemoveField(
            model_name='session',
            name='referenced_group',
        ),
        migrations.AddField(
            model_name='session',
            name='host_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_account', to='film_base.account'),
        ),
        migrations.AddField(
            model_name='session',
            name='host_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film_base.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='film_base.Account'),
        ),
    ]
