# Generated by Django 3.2 on 2021-04-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_base', '0003_auto_20210416_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(blank=True, choices=[['gift', 'Movie as gift!'], ['date', 'Movie for a date!'], ['event', 'Plan a movie']], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='finish_at',
            field=models.DateTimeField(),
        ),
    ]
