# Generated by Django 3.2 on 2021-04-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_base', '0004_auto_20210416_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(to='film_base.Account'),
        ),
    ]
