# Generated by Django 3.2 on 2021-04-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_base', '0005_alter_session_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='finish_at',
        ),
    ]
