# Generated by Django 3.2 on 2021-04-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_base', '0006_remove_session_finish_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='host_account',
        ),
        migrations.RemoveField(
            model_name='session',
            name='host_group',
        ),
        migrations.RemoveField(
            model_name='session',
            name='participants',
        ),
        migrations.AddField(
            model_name='session',
            name='participant_accounts',
            field=models.ManyToManyField(to='film_base.Account'),
        ),
        migrations.AddField(
            model_name='session',
            name='participant_groups',
            field=models.ManyToManyField(to='film_base.Group'),
        ),
    ]
