# Generated by Django 3.2 on 2021-04-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_base', '0007_auto_20210417_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='participant_accounts',
            field=models.ManyToManyField(blank=True, to='film_base.Account'),
        ),
        migrations.AlterField(
            model_name='session',
            name='participant_groups',
            field=models.ManyToManyField(blank=True, to='film_base.Group'),
        ),
    ]
