# Generated by Django 3.2 on 2021-04-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_base', '0008_auto_20210417_0256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='VSession',
        ),
    ]
