# Generated by Django 3.2 on 2021-04-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_base', '0009_rename_session_vsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsession',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
