# Generated by Django 3.2 on 2021-04-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_base', '0010_vsession_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsession',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
